### ISSUE TITLE
Class 'Hybrid_Provider_Model' not found

### ISSUE THREAD

**Issue by luizpaulofranz** [feelinc/magento2-social-login#3]
Hi, I'm working in a server with php 7.0.25 and magento 2.2.1.

I've installed the module and run **bin/magento setup:upgrade** successfully, but when I try to run **bin/magento setup:di:compile**, the following message is printed:

`MiBPHP Fatal error:  Class 'Hybrid_Provider_Model' not found in /var/www/html/app/code/Sulaeman/SocialLogin/Provider/Thirdparty/Facebook.php on line 26`

Thanks.

**Comment by feelinc** [comment]
Have you tried installing hybridauth/hybridauth version 2.9.x via composer? as described on the description.

**Comment by luizpaulofranz** [comment]
Sorry, my mistake.

To install it, just execute:
`composer require hybridauth/hybridauth`

Thanks!
