### ISSUE TITLE
If we click on facebook button its redirecting to 404 page

### ISSUE THREAD

**Issue by dilipathreya** [feelinc/magento2-social-login#4]
HI
I have installed the social login extension to my local.
Created the a Facebook app called myapp.
App Domains: localhost
site URL : http://localhost/local/  (My magento instance name is local)
Valid OAuth redirect URIs : http://localhost:local

In Client OAuth Settings : I have made yes for Client OAuth Login ,Web OAuth Login,  Embedded Browser OAuth Login.
And another two options to no (Force Web OAuth Reauthentication,Use Strict Mode for Redirect URIs).
These are the settings i made.
But if i click on the facebook button it is going to 404 page 
http://localhost/local/sociallogin/auth/login/provider/facebook/?back=http%3A%2F%2Flocalhost%2Flocal%2Fcustomer%2Faccount%2Flogin%2F
Its redirecting to this url.

Could you please help me in resolving this issue.Any thing i need to change please suggest.

**Comment by dilipathreya** [comment]
Magento version is 2.1.7

**Comment by dilipathreya** [comment]
Valid OAuth redirect URIs : http://localhost/local

**Comment by dilipathreya** [comment]
Now i am getting this error:

URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.

**Comment by zenomordiante** [comment]
You can't test Facebook Login with local path. Facebook check if website is valid, and I don't think that it can discover your local pc.

**Comment by feelinc** [comment]
Hi,
Please read @zenomordiante explanation, and thanks for the help.
I'm closing this issue.
