### ISSUE TITLE
Decompile Error

### ISSUE THREAD

**Issue by renyr** [feelinc/magento2-social-login#5]
After running sudo php bin/magento setup:di:compile, it throws an error as follows

PHP Fatal error:  Class 'OAuth2Client' not found in /var/www/html/wd/app/code/Sulaeman/SocialLogin/Provider/Thirdparty/Paypal/PaypalOAuth2Client.php on line 23

Please help me to fix it.

**Comment by zenomordiante** [comment]
Hi,
do you have installed dipendendence?

PHP 7.0.12, I think should also working in PHP 5.5.9 and above.
hybridauth/hybridauth version 2.9.x . Install it using composer first.

Go here to install:
https://github.com/hybridauth/hybridauth/tree/v2.9.6

**Comment by feelinc** [comment]
Hi,
Please follow @zenomordiante explanation, and thanks for your help.
I'm closing this issue.
